# Generated by Django 5.1.6 on 2025-02-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_category_remove_user_another_field_questions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
